### ISSUE TITLE
Module build error

### ISSUE THREAD

**Issue by ArielAleksandrus** [isopen/ngx-cable#4]
![screenshot from 2018-06-10 22 39 45](https://user-images.githubusercontent.com/10962902/41209073-4934cb10-6cff-11e8-8fff-61348228cafd.png)

Hello, guys. I've got this error while trying to use NgXCable with Angular 6

**Comment by isopen** [comment]
You are welcome

You can try using this config https://github.com/isopen/soc/blob/master/frontend/src/tsconfig.app.json
https://github.com/isopen/soc/blob/master/frontend/package.json
`ng serve`

**Comment by quentinbt** [comment]
Hi, same here, plus doesn't work with lazy loading

**Comment by isopen** [comment]
@quentinbt Please open a new ticket. The answer to the current question is presented above.

Thanks
