### ISSUE TITLE
Peer Dependencies for Angular 6

### ISSUE THREAD

**Issue by haynescw** [isopen/ngx-cable#5]
Is there any way you could update the peer dependency so I can use this with Angular 6?

**Comment by isopen** [comment]
eg: https://github.com/isopen/soc/tree/master/frontend (angular 6)
Probably the warning in the console is associated with the release of new versions of `rxjs`.
There is some incompatibility in `broadcaster.ts` with the new version of `rxjs`.
You need to wait for version `ngx-cable 1.2.5`

**Comment by haynescw** [comment]
When is the new version planned to be released?

**Comment by isopen** [comment]
New release has been published. Version `ngx-cable@1.2.5`
Describe please about the result.

Thanks

**Comment by haynescw** [comment]
Awesome!
