### ISSUE TITLE
node_modules/ngx-cable/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

### ISSUE THREAD

**Issue by medinarodel** [isopen/ngx-cable#6]
Hi!

Getting error when importing the NgXCableModule.

node_modules/ngx-cable/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

"typescript": "~2.7.2"
"@angular/cli": "~6.0.7",
"@angular/core": "^6.0.3",

**Comment by isopen** [comment]
eg:
https://github.com/isopen/soc/blob/master/frontend/src/tsconfig.app.json

**Comment by medinarodel** [comment]
By doing this, it will require me to do this:

```javascript
  "include": [
    "../node_modules/ngx-cable/*.ts",
    "./**/*.ts",
  ]
```

Which I am not sure about the side effect like if the app size will be bigger when compiled.

**Comment by medinarodel** [comment]
Anyway, above is the fix. Closing this ticket.
