### ISSUE TITLE
Version 1.2.8 has not been published

### ISSUE THREAD

**Issue by iblue** [isopen/ngx-cable#7]
Hi,

https://www.npmjs.com/package/ngx-cable still shows 1.2.7 as the latest version. The repo contains 1.2.8. When I try to use 1.2.7, I get:

> ERROR in node_modules/ngx-cable/broadcaster.ts(2,10): error TS2305: Module '"/home/iblue/git/aponow/ionic/node_modules/rxjs/Subject"' has no exported member 'Subject'.

I think this has been fixed in 1.2.8. So could you please publish it? Thanks!

**Comment by isopen** [comment]
Commit https://github.com/isopen/ngx-cable/commit/7e425d71b501860fd6d618692b9490f58defbe1f is a preparatory stage.

Try this usage example: https://github.com/isopen/soc/blob/master/frontend/package.json

**Comment by isopen** [comment]
@iblue Try installing `rxjs-compat`
https://www.npmjs.com/package/ngx-cable/v/1.2.9
